kind: pipeline
type: docker
name: default

steps:
  - name: frontend
    image: node
    volumes:
      - name: www
        path: /var/www
    commands:
      - npm install
      - npm run build
      - rm /var/www/* -rf
      - cp ./dist/* /var/www -r

volumes:
  - name: www
    host:
      path: /media/stefan/nginx/www

trigger:
  event:
    - tag